### ISSUE TITLE
todonotes out of page

### ISSUE THREAD

**Issue by balabi0github** [henrikmidtiby/todonotes#16]
First, thank you very much for this wonderful package. 

I encounter this problem. That is sometimes the notes get out of the page like this 

![2016-05-21_000520](https://cloud.githubusercontent.com/assets/11294083/15434230/811b6d0c-1ee8-11e6-8606-13d5f742082a.png)

I am using Revtex, and compiled with xelatex 

\documentclass[aps,prb,preprint,superscriptaddress,amsmath,amssymb]{revtex4-1}

**Comment by henrikmidtiby** [comment]
Great that you like to use the package.

Regarding your problem with todonotes going off the page.
I have no direct solution to the problem, as the todonotes are inserted by the marginpar command.
Marginpar does apparently not consider the height of the element to be inserted in the margin. 

You could try to use luatodonotes instead of the todonotes package.
luatodonotes uses lua to improve the placement of inserted todonotes.

**Comment by tsbertalan** [comment]
There was some [discussion on stackexchange](https://tex.stackexchange.com/questions/666950/todonotes-margin-note-runs-off-the-page). The workaround is to do something like
\vspace{-18em}
\todo{long comment here near end of page in surrounding text}
\vspace{18em}

Switching to luatodonotes does seem like a better solution to me (and correspondingly to the "LuaLaTeX' compiler on overleaf), since otherwise this problem comes up all the time.
