### ISSUE TITLE
feature to delete or rename .tdo file

### ISSUE THREAD

**Issue by Arznnn** [henrikmidtiby/todonotes#46]
I would like a feature to delete the automaticly created .tdo file after compiling. Or a feature to rename the file automaticly(.filename.tdo) so that it is invisible like the .log or .aux files from Latex.

**Comment by henrikmidtiby** [comment]
Thanks for the suggestion.
The .tdo file is needed for generating the listoftodos and therefore I would like to keep that file.

To me it seems that the issue is that the file is visible from your latex editor.
The logical place to make the file invisible would be in the editor, to the file is treated just like .log, .lof, .aux, .bbl, .blg and similar files that latex generate when compiling documents.

Which latex editor are you using?

**Comment by Arznnn** [comment]
My editor of coice is Vim but that ist not the where the file is bothering me. I see it in my filemanager ranger and in the filesystem. That is why i thought of putting a . infront of the file name.

**Comment by henrikmidtiby** [comment]
The standard files in latex do not have a period in front of them (e.g. filename.log and filename.aux).
How to you hide these files or have they been removed?

**Comment by Arznnn** [comment]
I solved it and it was easy.
Just add tdo in to the rangerrc to hidden_filter

Thank you for your help and I'm sorry taking your time.
