### ISSUE TITLE
Error on todo with empty line when using \listoftodos

### ISSUE THREAD

**Issue by saschakr** [henrikmidtiby/todonotes#52]
I guess I found an issue on this package.

My dummy.tex file
```
\documentclass{article}
\usepackage{todonotes}
\begin{document}

\listoftodos
Lorem ipsum
\todo{
    Hello
    World
}
\end{document}
```

so this file is working.
When adding a empty line between `Hello` and `World` this will break.

Example:

```
\todo{
    Hello

    World
}
```
so the `dummy.tdo` contains following input: 

```
\contentsline {todo}{ Hello \par World }{1}%
```

Running `lualatex` on this following error is thrown: 

```
ABD: EveryShipout initializing macros (./minted.tdo
Runaway argument?
{ Hello 
! Paragraph ended before \@dottedtocline was complete.
<to be read again> 
\par 
l.1 \contentsline {todo}{ Hello \par
                                   World }{1}%
? 
! Emergency stop.
<to be read again> 
\par 
l.1 \contentsline {todo}{ Hello \par
                                   World }{1}%
 1053 words of node memory still in use:
   20 hlist, 9 rule, 1 local_par, 1 dir, 6 glue, 5 kern, 2 penalty, 9 glyph, 55
 attribute, 48 glue_spec, 55 attribute_list, 1 write, 16 pdf_literal, 17 pdf_co
lorstack nodes
   avail lists: 2:12,4:1,5:4,7:1,9:2
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on minted.log.
```

I can fix this issue by adding a simple whitespace in this line, but VSCode will automatically remove trailing whitespaces.

**Comment by henrikmidtiby** [comment]
The problem is that you try to insert multiline content into the list of
todos, which is not possible.
I do not want to pursue fixing that issue, as it is buried too deep in the
tex kernel.

However you have a few options for getting around this.
Either provide the "nolist" option to the todo command og provide the text
to insert in the list of todos through the caption option.

\todo[nolist]{
Hello

World}


\todo[caption={Hello world}]{
Hello

World}


So the entire example will be.


\documentclass{article}
\usepackage{todonotes}
\begin{document}

\todo[nolist]{
Hello

World}


\todo[caption={Hello world}]{
Hello

World}
\end{document}

**Comment by FrankMittelbach** [comment]
It is actually not that much of a problem. Instead of a blank line you could use `\endgraf` (which is accepted) or one could allow for this with a slight modification the way dottedcontentline is called:
```
\documentclass{article}
\usepackage{todonotes}
\makeatletter
\renewcommand{\l@todo}[1]
             {\begingroup
               \def\par{\\\relax}\protected@xdef\todo@tocarg{#1}\endgroup
               \@dottedtocline{1}{0em}{2.3em}{\todo@tocarg}}
\makeatother
\begin{document}

\listoftodos
Lorem ipsum
\todo{
    Hello
   
    World
}
\end{document}
```

One could use a different definition for `\par` but making it a newline gives a reasonable result.

**Comment by saschakr** [comment]
@FrankMittelbach I'll give it a try.
Is there a reason why this is not the default behavoir?

**Comment by FrankMittelbach** [comment]
> Is there a reason why this is not the default behavoir?

historical to some extent. 

LaTeX doesn't support paragraphs inside of section headings so \sectiom{Hello \par World} gives you an error And several paragraphs inside a heading do make little sense. Thus, no point in allowing \par inside of toc entries (as they can't appear there). Now \todo uses the toc mechanism but it accepts \par in its argument hence the problem.
