### ISSUE TITLE
Undefined control sequence with setcounter command in todo 

### ISSUE THREAD

**Issue by Piaoshi** [henrikmidtiby/todonotes#61]
\documentclass{article}
\usepackage{todonotes}
\begin{document}
\newcounter{mycounter}
If I use \verb|\setcounter{mycounter}{0}| in \verb|\todo{}| 
\todo{\setcounter{mycounter}{1}blabla}, there is a undefined control sequence. However, if I ignore it, the result is OK。 
\end{document}

**Comment by henrikmidtiby** [comment]
Thanks for raising this issue and providing a nice small example that can reproduce the problem.

I have tried to make your small example even smaller, which has lead to the example shown below. The example does not use the todonotes package, but triggers the exact same error message as the original example did. If you want to get rid of the example, you can add `\protect` before the `\setcounter` command.
```
\documentclass{article}
\usepackage{calc}

\newcounter{mycounter}
\begin{document}
asd

%\addcontentsline{tdo}{todo}{\protect\setcounter{mycounter}{1}}
\addcontentsline{tdo}{todo}{\setcounter{mycounter}{1}}
\end{document}
```

An alternative way to get rid of the problem is to avoid to provide the `\setcounter` command to the `\addcontentsline` command. This can be achieved by specifying the `caption` option for the `todo` command, like shown below.

```
\todo[caption]{\setcounter{mycounter}{1} Blah}
```
