### ISSUE TITLE
\ifmmode doesn't work in the Todo list

### ISSUE THREAD

**Issue by AlbertNashr** [henrikmidtiby/todonotes#63]
Feeding
```
\documentclass{article}
\pagestyle{empty}
\usepackage{todonotes}
\begin{document}%
\listoftodos
\todo{\(\ifmmode MATH \else TEXT\fi\)}%%% $…$ instead of \(…\) fails as well.
\end{document}
```
to `pdflatex` yields

![mwe](https://user-images.githubusercontent.com/116845534/209454470-efc0304d-6574-46d1-ba16-8e421e02bc06.png)

However, the expected outcome is 𝑀𝐴𝑇𝐻 printed in the Todo list, and not 𝑇𝐸𝑋𝑇.

Why does this happen, who is the culprit, and what to do?

The same issue: https://tex.stackexchange.com/questions/669576 .

**Comment by eg9** [comment]
This is not a problem of `todonotes`.

**Comment by AlbertNashr** [comment]
@henrikmidtiby Given @eg9's comment and the answers on stackexchange, please consider extending the documentation of todonotes in regard to this.

**Comment by FrankMittelbach** [comment]
marginpars have moving arguments and in moving arguments things break if they are fragile. That is a general documented fact in LaTeX (eg Lamport's manual or LaTeX Companion or ...).. Marginpars are used by todonotes and therefore its arguments are moving arguments. What todonotes could document is to remind people that the argument is a moving argument and that one therefore can't use fragile commands inside, but would that have helped? I have my doubts, but it certainly wouldn't do any harm to make that remark.

The underlying problem is that `\ifmmode...` is a programming construct that is fragile and should not be used in documents (by users) but only in package code that ensures that it remains hidden within a robust command but there are plenty other fragile commands or commands that should not be used on user level and that is not something todonote can reasonably document.

**Comment by AlbertNashr** [comment]
@FrankMittelbach My usage is a semi-user level: I tried to determine the origin of a cryptic error message apparently coming from the combination of some macros in the preamble of my full-length, non-MWE document. The MWE in the original post above is a cleaned up version of my full-length stuff; there, neither `\todo` nor `\ifmmode` occur verbatim in the scope of `\begin{document}...\end{document}`. In the documentation of todonotes I found nothing related to `\ifmmode`. I don't see any occurrence of "fragile" either. If you think that there are plenty of other fragile constructs that'd break similarly, you could say something along the lines of, e.g., "Fragile constructs inside `\todo{...}` are not expected to work properly in the contents generated by `\listoftodos`. For example, `\todo{\(\ifmmode MATH\else TEXT\fi\)}` may produce 𝑇𝐸𝑋𝑇 in the Todo list." Would that have helped, you may ask again? In my opinion, yes. If it's not reasonably possible to document all fragile commands that break, it's reasonably possible to provide an example.

**Comment by FrankMittelbach** [comment]
> For example, `\todo{\(\ifmmode MATH\else TEXT\fi\)}` may produce 𝑇𝐸𝑋𝑇 in the Todo list." into the documentation. Would that have helped, you may ask again? In my opinion, yes.

that example would have helpd in your case, but for starters it is not LaTeX code that should appear anywhere in a document and should therefore not be given as an example. But would it have helped if it would have been a proper example using LaTeX constructs, such as
```
\todo{\renewcommand\foo{...} ....}
```
or anything else really. Probably not because you wouldn't have made the connection, or would you?

> If it's not reasonably possible to document all fragile commands that break, it's reasonably possible to provide an example.

Literally anything that partially expands in a moving argument and can therefore not be used, which is an endless list if you go down to programming constructs that are not properly protected (as they should). This is why I'm saying  that a reminder that `\todo` has moving arguments doesn't hurt this is really as best as you can go.

Your code would break identically inside `\section` inside `\caption` and various other core commands that have "moving arguments" and it would break various packages that have commands with moving arguments.

**Comment by AlbertNashr** [comment]
> that example would have helpd in your case, but for starters

If any starter has complained about a fragile, non-`\ifmmode` construct inside `\todo{…}` that is also proper™, i.e., that is allowed™ to be used between `\begin{document}…\end{document}` of LaTeX, please feel free to take the starter's example. Makes sense. 

However, `\todo{\renewcommand\foo{…}…}` has the problem that `\todo[…]{\renewcommand{…}{…}…}` does occur in the documentation in § 1.8.6 on p. 15. It works in an MWE at least for me (orelse I miss the point): `\todo[caption={Half baselineskip}, size=\small]{\renewcommand{\baselinestretch}{0.5}\selectfont Half baselineskip\par}`. So, it's a wrong example of what would break if you put it that plainly. On the contrary, `\todo{\(\ifmmode MATH \else TEXT\fi\)}` is a real-world occurrence at least in the sense that some (huge) piece of real LaTeX code has been reduced to it.

As of now, "moving" is also absent from the documentation.

So, as now the documentation seems silent about this issue in general, you or the author should please feel free to improve it the way you feel appropriate or most informing or educative.

Off-topic: “Placing todonotes in footnotes throws a lot of errors.” in § 1.6.7 is false in certain cases: `\footnote{TESTF\todo[inline]{TESTT}}` works just fine for me.

**Comment by FrankMittelbach** [comment]
> > that example would have helpd in your case, but for starters
> 
> If any starter has complained about a fragile, non-`\ifmmode` construct inside `\todo{…}` that is also proper™, i.e., that is allowed™ to be used between `\begin{document}…\end{document}` of LaTeX, please feel free to take the starter's example. Makes sense.

for starters doesn't refer to beginners of LaTeX, it is a phrase meaning "for a start"  or "to begin with", so pardon my English.

> 
> However, `\todo{\renewcommand\foo{…}…}` has the problem that `\todo[…]{\renewcommand{…}{…}…}` does occur in the documentation in § 1.8.6 on p. 15. It works in an MWE at least for me (orelse I miss the point): `\todo[caption={Half baselineskip}, size=\small]{\renewcommand{\baselinestretch}{0.5}\selectfont Half baselineskip\par}`. So, it's a wrong example of what would break if you put it that plainly. On the contrary, `\todo{\(\ifmmode MATH \else TEXT\fi\)}` is a real-world occurrence at least in the sense that some (huge) piece of real LaTeX code has been reduced to it.

That examples uses `caption=`, i.e., it has its own caption text (which is the moving argument) not containing `\renewcommand`. Plug `\renewcommand` into your example to see how it breaks.

> As of now, "moving" is also absent from the documentation.

that's what I said, didn't I? I might be helpful to remind people that todoes have (or can have) moving arguments whenever they transport their data from one place to another (ie to a list of todos)

> Off-topic: “Placing todonotes in footnotes throws a lot of errors.” in § 1.6.7 is false in certain cases: `\footnote{TESTF\todo[inline]{TESTT}}` works just fine for me.

guess your example with "inline" should be mentioned there as an alternative to resolve the problem of \todo being unusable inside of boxes (or footnotes).

**Comment by AlbertNashr** [comment]
@FrankMittelbach Alright, got it, thx!

> > As of now, "moving" is also absent from the documentation.

> that's what I said, didn't I? 

Earlier, you said not exactly the same: “What todonotes could document is to remind people that the argument is a moving argument and that one therefore can't use fragile commands inside”.  Anyhow, let's not split hairs; I got your message.  If you or the author or whoever wishes to improve, please feel free.

**Comment by henrikmidtiby** [comment]
Thanks for raising the issue.
I will try to improve the documentation for the todonotes package based on
your discussion.

Best regards
Henrik

tir. 27. dec. 2022 kl. 20.56 skrev AlbertNashr ***@***.***>:
