### ISSUE TITLE
todo in caption of float breaks placement of todos in series

### ISSUE THREAD

**Issue by dflvunoooooo** [henrikmidtiby/todonotes#75]
It seems to be impossible that, I can set two todos in series with the option to also enable me to set todos inside the caption of floats.  If `\let\marginpar\marginnote` is disabled, the todos are placed where they should, but will fail if placed inside a caption.

![Screenshot_20240306_232008](https://github.com/henrikmidtiby/todonotes/assets/32816598/0a0742c9-7552-4d41-a5bf-63c9b5e0db9a)

```
\documentclass{scrartcl}

\usepackage{todonotes}
\usepackage{marginnote} 
\let\marginpar\marginnote  

\begin{document}
Mauris lacinia lorem sit amet ipsum. Nunc quis urna dictum turpis accumsan semper.\todo{Change something.}\todo{Change something else.}


\begin{table}
    \centering
    \caption{Test \todo{Test something.}\todo{Test2}}%
    \label{tab:test}
    \begin{tabular}{cc}
        Test & Test \\
        Test & Test \\
    \end{tabular}
\end{table}
\end{document}
```

**Comment by henrikmidtiby** [comment]
It is a known issue, that I currently do not have a suitable solution for.

By default the todonotes package use the marginpar command to insert todonotes in the margin. The benefit of using marginpar is that the command ensures that the inserted notes do not overlap. The downside is that marginpar does not work in floating environments (like inside figures).

The approach of using marginnote instead of marginpar solves the issue of marginpar not working in floating environments. However the marginnote command is not able to avoid overlap between inserted notes.

If you use lualatex, the luatodonotes package might solve you issue, as it implements the note placement algoritm from scratch. 

My personal solution is to insert todos as inline, when I have to put them into floating environments. This alters the appearance of the todo, but it also works in floating environments.

`\todo[inline]{Todo in a figure caption.}  `
